services:
  app:
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PORT=3000
    ports:
      - "3000:3000"
    command: npm run start:prod
    networks:
      - nestjs-network

  db:
    networks:
      - nestjs-network